### ISSUE TITLE
9: Syntax error: newline unexpected

### ISSUE THREAD

**Issue by gitdy-up** [sfiorini/NordVPN-Wireguard#10]
Hi,

No mater what argument I am using, when running the script (ex. $ ./NordVpnToWireguard.sh --city Berlin) I receive the following error: 9: Syntax error: newline unexpected

Can you please help?

Thank you very much!

**Comment by ALEXSANPEDRO** [comment]
> Hi,
> 
> No mater what argument I am using, when running the script (ex. $ ./NordVpnToWireguard.sh --city Berlin) I receive the following error: 9: Syntax error: newline unexpected
> 
> Can you please help?
> 
> Thank you very much!
same issue. How you solve it?

**Comment by Brewer7** [comment]
I have the same problem can you please share the solution.
