### ISSUE TITLE
Add --group argument to script

### ISSUE THREAD

**Issue by hongkongkiwi** [sfiorini/NordVPN-Wireguard#8]
This is fantastic, thank you.

Is it possible to add an addition so that I can select the different category of servers?

In my nordvpn app I can select groups like this:  `nordvpn groups`

So I was thinking we could add the --group arg to this script, so it would would additionally filter the output, e.g. `NordVpnToWireguard -c US -g P2P`

```
Africa_The_Middle_East_And_India
Onion_Over_VPN
Asia_Pacific
P2P
Double_VPN
Standard_VPN_Servers
Europe
The_Americas
```

**Comment by hongkongkiwi** [comment]
I've added this with a pull request: #9 , this allows P2P servers (or other groups) to be specified

**Comment by sfiorini** [comment]
Thanks, version 0.2.0 adds support for groups.
